#!/bin/bash
##-->>HINABILITAR UFW
ufw disable
##-->>CHECK IP
MEU_IP=$(wget -qO- ifconfig.me)
echo "$MEU_IP" >/tmp/IP
##-->>REINICIAR DROPBEAR
service dropbear stop &>/dev/null
service ssh restart &>/dev/null
sed -i "s/=1/=0/g" /etc/default/dropbear &>/dev/null
service dropbear restart &>/dev/null
sed -i "s/=0/=1/g" /etc/default/dropbear &>/dev/null
##-->> AUTO BADVPN
if [[ -e "/etc/SCRIPT-LATAM/PortM/Badvpn.log" ]]; then
    portasx=$(cat /etc/SCRIPT-LATAM/PortM/Badvpn.log)
    totalporta=($portasx)
    for ((i = 0; i < ${#totalporta[@]}; i++)); do
        screen -d -m -S badvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:${totalporta[$i]} --max-clients 1000 --max-connections-for-client 10

    done
fi
